/**
 * system/codex-data.js — GESP 1～3 级相关常识 / 考点词条
 */
(function (global) {
  "use strict";

  const CODEX_ENTRIES = [
    // ===== 一级：发展史 =====
    { id: "hist_abac", level: 1, cat: "history", title: "从算盘到机械计算机", emoji: "🧮",
      summary: "计算工具的早期形态",
      body: "算盘等工具辅助人工计算。17 世纪帕斯卡、莱布尼茨等制成机械计算装置。它们尚未具备现代「存储程序」能力，但说明计算可以机械化。" },
    { id: "hist_babbage", level: 1, cat: "history", title: "巴贝奇与分析机", emoji: "⚙️",
      summary: "可编程思想的构想",
      body: "巴贝奇设计差分机与分析机，设想用卡片控制运算步骤。阿达·洛夫莱斯为其撰写算法描述，常被视为程序设计思想的早期代表。" },
    { id: "hist_turing", level: 1, cat: "history", title: "图灵与可计算性", emoji: "📜",
      summary: "算法能算什么",
      body: "图灵机用纸带与状态规则刻画「可计算」。图灵奖是计算机领域重要荣誉。GESP 强调：算法是有穷、确定、可执行的步骤序列。" },
    { id: "hist_von", level: 1, cat: "history", title: "冯·诺依曼结构", emoji: "📐",
      summary: "五大部件与存储程序",
      body: "运算器、控制器、存储器、输入、输出。程序与数据放在存储器中，CPU 按地址取指令执行。现代通用计算机大多仍遵循这一基本框架。" },
    { id: "hist_eniac", level: 1, cat: "history", title: "电子计算机的诞生", emoji: "🖥️",
      summary: "电子管时代",
      body: "20 世纪 40 年代出现以电子管为主的电子计算机（如 ENIAC），体积大、功耗高，但速度远超机械装置。" },
    { id: "hist_gen", level: 1, cat: "history", title: "计算机四代简表", emoji: "📊",
      summary: "按主要元件划分",
      body: "1 代电子管；2 代晶体管；3 代中小规模集成电路；4 代大规模/超大规模集成电路。软件则从机器语言、汇编发展到高级语言与操作系统普及。" },
    { id: "hist_cn", level: 1, cat: "history", title: "我国计算机事业简记", emoji: "🇨🇳",
      summary: "一级常考点",
      body: "了解我国从仿制到自主研制电子计算机的大致历程即可。考试多考「常识性时间与意义」，不必死记所有型号参数。" },

    // ===== 一级：信息 =====
    { id: "info_bit", level: 1, cat: "info", title: "比特与字节", emoji: "🪙",
      summary: "信息度量",
      body: "1 bit 取值 0/1；8 bit = 1 Byte。容量常用 KB、MB、GB、TB（教学中常按 1024 进位）。区分存储容量与网速单位（如 Mbps）。" },
    { id: "info_encode", level: 1, cat: "info", title: "字符与多媒体编码", emoji: "🔤",
      summary: "现实信息→0/1",
      body: "ASCII、Unicode 等表示字符。声音、图像经采样、量化成为数字数据。没有约定的编码规则，就无法正确解码。" },
    { id: "info_analog", level: 1, cat: "info", title: "模拟信号与数字信号", emoji: "📡",
      summary: "连续与离散",
      body: "模拟信号连续变化；数字信号取离散电平。计算机内部主要处理数字信号。ADC/DAC 完成模数与数模转换。" },

    // ===== 一级：硬件 =====
    { id: "hw_cpu", level: 1, cat: "hardware", title: "CPU", emoji: "🧠",
      summary: "运算与控制中心",
      body: "取指、译码、执行。性能与主频、核心数等有关，但算法与 I/O 同样关键。一级抓住「执行程序的核心部件」即可。" },
    { id: "hw_mem", level: 1, cat: "hardware", title: "内存与外存", emoji: "💾",
      summary: "工作台与仓库",
      body: "内存快、断电易失；外存大、可长期保存。程序运行时把需要的数据调入内存。" },
    { id: "hw_io", level: 1, cat: "hardware", title: "输入输出设备", emoji: "⌨️",
      summary: "人机接口",
      body: "输入：键鼠、摄像头等；输出：显示器、打印机等。scanf/printf 对应标准输入与标准输出的软件层面。" },
    { id: "hw_bus", level: 1, cat: "hardware", title: "主板与总线", emoji: "🔌",
      summary: "部件互联",
      body: "主板连接各部件；总线是共享传输通路。理解「有通路才能交换数据」。" },

    // ===== 一级：软件 =====
    { id: "sw_os", level: 1, cat: "software", title: "操作系统", emoji: "🪟",
      summary: "资源管理与接口",
      body: "管理 CPU、内存、文件、设备，提供操作界面，支持多程序运行。Windows、Linux、macOS、安卓等是常见 OS。" },
    { id: "sw_lang", level: 1, cat: "software", title: "语言层次", emoji: "📝",
      summary: "机器·汇编·高级",
      body: "机器语言是 0/1 指令；汇编用助记符；高级语言（C++ 等）需编译或解释。GESP 一级主学 C++ 基础语法与输入输出。" },
    { id: "sw_compile", level: 1, cat: "software", title: "编译与链接", emoji: "🔨",
      summary: "源程序→可执行",
      body: "源文件经编译检查语法并翻译，再链接得到可执行文件。先读懂报错位置，再修改。" },
    { id: "sw_file", level: 1, cat: "software", title: "文件与路径", emoji: "📁",
      summary: "外存组织",
      body: "文件有名与扩展名；文件夹分层组织；路径描述查找方式。注意备份与分类。" },

    // ===== 一级：数制 =====
    { id: "num_bin", level: 1, cat: "number", title: "二进制↔十进制", emoji: "🔢",
      summary: "一级必会",
      body: "十→二：除 2 取余；二→十：按权相加。八/十六进制常作二进制简写（3 位、4 位一组）。" },
    { id: "num_why", level: 1, cat: "number", title: "为何用二进制", emoji: "⚡",
      summary: "电路与可靠性",
      body: "两种稳态表示 0/1 可靠，逻辑运算易实现。人习惯十进制，故输入输出常做转换。" },
    { id: "num_hex", level: 1, cat: "number", title: "十六进制阅读", emoji: "🔠",
      summary: "压缩书写二进制",
      body: "0–9、A–F 表示 0–15。每位对应 4 位二进制。地址、颜色值中常见。" },

    // ===== 一级：网络 =====
    { id: "net_what", level: 1, cat: "network", title: "计算机网络", emoji: "🌐",
      summary: "互联与共享",
      body: "多台独立设备经通信线路连接，实现资源共享与信息传递。局域网、广域网；互联网是网际网。" },
    { id: "net_hw", level: 1, cat: "network", title: "网卡·交换·路由", emoji: "📶",
      summary: "常见设备角色",
      body: "网卡接入网络；交换机局域网转发；路由器连接不同网络并选路。" },
    { id: "net_ip", level: 1, cat: "network", title: "IP 与域名", emoji: "🏠",
      summary: "寻址",
      body: "IP 是逻辑地址；域名经 DNS 解析为 IP。记住「名字→地址→到达」。" },
    { id: "net_proto", level: 1, cat: "network", title: "协议与分层", emoji: "📬",
      summary: "通信规则",
      body: "协议是双方约定。分层使问题分解（应用、传输、网络等）。一级建立「无协议则难互通」的概念。" },
    { id: "net_safe", level: 1, cat: "network", title: "网络安全意识", emoji: "🔒",
      summary: "使用底线",
      body: "强密码、更新系统、慎点链接、保护隐私。安全是使用网络的一部分。" },
    { id: "soc_ethics", level: 1, cat: "society", title: "信息伦理与版权", emoji: "⚖️",
      summary: "合法使用",
      body: "尊重隐私与版权；不传播违法信息；开源许可也是使用约定。" },
    { id: "soc_role", level: 1, cat: "society", title: "信息技术与生活", emoji: "🏙️",
      summary: "数字化环境",
      body: "学习、支付、交通、医疗等依赖信息技术。学编程有助于理解数字世界如何构造。" },

    // ===== 一级：C++ 入门考点 =====
    { id: "cpp1_io", level: 1, cat: "cpp1", title: "scanf 与 printf 基础", emoji: "🖨️",
      summary: "一级核心",
      body: "printf 按格式串输出；scanf 按格式从标准输入读入并写入变量地址（注意 &）。常见格式：%d %f %c %s 以及宽度、精度如 %5d、%.2f。" },
    { id: "cpp1_type", level: 1, cat: "cpp1", title: "基本数据类型", emoji: "📦",
      summary: "int/float/char/bool",
      body: "整型、浮点、字符、布尔等。注意取值范围与类型匹配；赋值与运算时的隐式转换可能造成精度或截断问题。" },
    { id: "cpp1_op", level: 1, cat: "cpp1", title: "运算符与表达式", emoji: "➕",
      summary: "算术·关系·逻辑",
      body: "注意 / 对整数是整除；% 取余；关系与逻辑用于条件。优先级记不清时用括号，考试常考混合表达式结果。" },
    { id: "cpp1_branch", level: 1, cat: "cpp1", title: "分支结构", emoji: "🌿",
      summary: "if / switch",
      body: "if-else 按条件选择路径；switch-case 适合多常量分支，注意 break。一级要能读懂分支后的输出结果。" },
    { id: "cpp1_loop", level: 1, cat: "cpp1", title: "循环结构", emoji: "🔁",
      summary: "for / while",
      body: "明确初值、条件、更新，避免死循环。能模拟循环变量变化并写出输出。嵌套循环要分清内外层。" },
    { id: "cpp1_seq", level: 1, cat: "cpp1", title: "顺序结构与流程", emoji: "➡️",
      summary: "从上到下执行",
      body: "没有分支循环时按书写顺序执行。读题时用「纸上跑程序」跟踪变量。" },

    // ===== 二级向 =====
    { id: "cpp2_array", level: 2, cat: "cpp2", title: "一维数组", emoji: "📚",
      summary: "二级重点",
      body: "相同类型元素的连续集合，下标常从 0 开始。注意越界、初始化、遍历。与循环结合完成统计、查找、最值。" },
    { id: "cpp2_string", level: 2, cat: "cpp2", title: "字符数组与字符串", emoji: "🧵",
      summary: "以 \\0 结尾的约定",
      body: "C 风格字符串以 '\\0' 结束。strlen、strcpy 等需理解其含义；输出与输入时注意空格与长度。" },
    { id: "cpp2_func", level: 2, cat: "cpp2", title: "函数基础", emoji: "🧩",
      summary: "声明·定义·调用",
      body: "参数传递、返回值、局部变量作用域。一级到二级过渡时，用函数拆分题目逻辑。" },
    { id: "cpp2_algo", level: 2, cat: "cpp2", title: "枚举与模拟", emoji: "🔍",
      summary: "二级常见思路",
      body: "按题意一步步模拟；或在小范围内枚举可能答案并验证。先保证正确，再考虑效率。" },
    { id: "cpp2_sort", level: 2, cat: "cpp2", title: "排序思想入门", emoji: "📶",
      summary: "比较与交换",
      body: "冒泡等简单排序帮助理解「比较—交换—有序」。知道有序后便于二分（若大纲要求）。" },
    { id: "cpp2_2d", level: 2, cat: "cpp2", title: "二维数组入门", emoji: "🗂️",
      summary: "行列下标",
      body: "按行/列遍历；与嵌套循环配合。注意边界与初始化。" },
    { id: "net2_osi", level: 2, cat: "network", title: "网络分层再认识", emoji: "📶",
      summary: "二级可扩展常识",
      body: "传输层（如 TCP/UDP）与网络层（IP）分工不同：可靠传输、端口与寻址、路由。应用层直接服务用户程序。" },
    { id: "hw2_storage", level: 2, cat: "hardware", title: "存储层次", emoji: "🧊",
      summary: "速度与容量的折中",
      body: "寄存器—缓存—内存—外存：越近 CPU 越快越贵越小。程序局部性使缓存有效。" },

    // ===== 三级向 =====
    { id: "cpp3_ptr", level: 3, cat: "cpp3", title: "指针入门概念", emoji: "👉",
      summary: "三级常见加深",
      body: "指针保存地址；* 与 & 的含义。数组名与指针关系、指针运算要谨慎。先画内存示意再写代码。" },
    { id: "cpp3_struct", level: 3, cat: "cpp3", title: "结构体", emoji: "🧱",
      summary: "组合数据",
      body: "把多个相关变量组成一种类型。便于表示学生、点、日期等对象。结合数组可做表格式数据。" },
    { id: "cpp3_rec", level: 3, cat: "cpp3", title: "递归初步", emoji: "🪞",
      summary: "自己调用自己",
      body: "必须有终止条件与向终止靠近的递归步。栈深度与重复计算是常见陷阱。先写递推再理解递归。" },
    { id: "cpp3_search", level: 3, cat: "cpp3", title: "查找与二分", emoji: "🎯",
      summary: "有序集合上的高效查找",
      body: "二分要求有序；每次排除一半。注意边界 mid、左右区间开闭。" },
    { id: "cpp3_comp", level: 3, cat: "cpp3", title: "复杂度直观", emoji: "⏱️",
      summary: "快慢数量级",
      body: "双重循环约 n² 级；二分约 log n 级。数据变大时，数量级比常数更重要。三级开始建立「估算」习惯。" },
    { id: "algo3_greedy", level: 3, cat: "cpp3", title: "贪心思路印象", emoji: "🎣",
      summary: "每步局部最优",
      body: "适用于能证明局部最优可导致全局最优的问题。不能想当然使用；先举反例检验。" },
    { id: "ds3_stack", level: 3, cat: "cpp3", title: "栈与队列印象", emoji: "🥞",
      summary: "后进先出 / 先进先出",
      body: "栈：括号匹配、表达式；队列：排队、缓冲。先理解规则，再在语言中用数组模拟。" },

    // ===== 考试方法 =====
    { id: "exam_read", level: 1, cat: "exam", title: "读题与模拟执行", emoji: "👀",
      summary: "所有级别通用",
      body: "看清输入输出格式、边界。用纸笔跟踪变量。输出空格与换行常决定对错。" },
    { id: "exam_iofmt", level: 1, cat: "exam", title: "格式化陷阱清单", emoji: "⚠️",
      summary: "一级高频",
      body: "缺 &；% 与类型不符；多余换行或空格；字段宽度与精度；字符串读入遇空格停止等。" },
    { id: "exam_time", level: 1, cat: "exam", title: "临场时间分配", emoji: "⏰",
      summary: "先稳后冲",
      body: "先做会的与分值稳的题；标记不确定题回看。留时间检查输出格式。" },
    { id: "exam_gesp", level: 1, cat: "exam", title: "GESP 一级考什么", emoji: "📋",
      summary: "大纲印象",
      body: "计算机基础常识 + C++ 一级语法（类型、表达式、分支、循环、基础输入输出等）。以正确理解与模拟执行为主，而非偏题怪题。" },
    { id: "exam_gesp2", level: 2, cat: "exam", title: "GESP 二级递进", emoji: "📋",
      summary: "数组与函数等",
      body: "在一级基础上加强数组、字符串、函数与综合题模拟能力。基础题仍不能丢。" },
    { id: "exam_gesp3", level: 3, cat: "exam", title: "GESP 三级递进", emoji: "📋",
      summary: "更复杂的逻辑与结构",
      body: "指针/结构体/递归等视大纲要求掌握；更强调算法思路与细心实现。常识网络硬件仍可能穿插。" }
  ];

  const CODEX_CATS = {
    history: { name: "发展史", emoji: "📚" },
    info: { name: "信息", emoji: "ℹ️" },
    hardware: { name: "硬件", emoji: "🖥️" },
    software: { name: "软件", emoji: "💿" },
    number: { name: "数制", emoji: "🔢" },
    network: { name: "网络", emoji: "🌐" },
    society: { name: "社会", emoji: "🏙️" },
    cpp1: { name: "一级C++", emoji: "1️⃣" },
    cpp2: { name: "二级拓展", emoji: "2️⃣" },
    cpp3: { name: "三级拓展", emoji: "3️⃣" },
    exam: { name: "应试", emoji: "📝" }
  };

  const CODEX_MILESTONES = [
    { id: "codex_5", needViewed: 5, mailId: "codex_spirit_seed" },
    { id: "codex_12", needViewed: 12, mailId: "codex_spirit_lantern" },
    { id: "codex_20", needViewed: 20, mailId: "codex_spirit_archive" },
    { id: "codex_35", needViewed: 35, mailId: "codex_spirit_legend" },
    { id: "codex_all", needViewed: 999, mailId: "codex_spirit_legend" }
  ];

  global.CODEX_DATA = { CODEX_ENTRIES, CODEX_CATS, CODEX_MILESTONES };
})(typeof window !== "undefined" ? window : globalThis);
